#include <iostream>
using namespace std;

int main() {
    const int SIZE = 10;
    unsigned int numbers[SIZE];

    cout << "Enter 10 unsigned integers:\n";
    for (int i = 0; i < SIZE; ++i) {
        cin >> numbers[i];
    }

    unsigned int min = numbers[0];
    unsigned int max = numbers[0];

    for (int i = 1; i < SIZE; ++i) {
        if (numbers[i] < min)
            min = numbers[i];
        if (numbers[i] > max)
            max = numbers[i];
    }

    cout << "\nNumbers entered: ";
    for (int i = 0; i < SIZE; ++i)
        cout << numbers[i] << " ";

    cout << "\nMinimum value: " << min;
    cout << "\nMaximum value: " << max << endl;

    return 0;
}


// This program was generated by ChatGPT. Using ChatGPT to generate code all the time can cause learning issues down the road,
// as well as the fact that you now know less about how to actually write code efficiently and correctly.

// However, you can use LLMs to help you ethically by using them to speed up your workflow, research new things, and/or brainstorm logic for your code.